/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as CharactersIndexRouteImport } from './routes/characters.index'
import { Route as DirectoryIndexRouteImport } from './routes/directory.index'
import { Route as DirectoryCampaignIdRouteImport } from './routes/directory.$campaignId'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as CharactersCharacterIdBuildRouteImport } from './routes/characters.$characterId.build'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryCampaignIdRoute = DirectoryCampaignIdRouteImport.update({
  id: '/directory/$campaignId',
  path: '/directory/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCharacterIdBuildRoute =
  CharactersCharacterIdBuildRouteImport.update({
    id: '/characters/$characterId/build',
    path: '/characters/$characterId/build',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/directory/$campaignId': typeof DirectoryCampaignIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/characters/$characterId/build': typeof CharactersCharacterIdBuildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/directory/$campaignId': typeof DirectoryCampaignIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/characters/$characterId/build': typeof CharactersCharacterIdBuildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/directory/$campaignId': typeof DirectoryCampaignIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/characters/$characterId/build': typeof CharactersCharacterIdBuildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns/$campaignId'
    | '/directory/$campaignId'
    | '/join/$code'
    | '/campaigns/'
    | '/characters/'
    | '/directory/'
    | '/characters/$characterId/build'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns/$campaignId'
    | '/directory/$campaignId'
    | '/join/$code'
    | '/campaigns'
    | '/characters'
    | '/directory'
    | '/characters/$characterId/build'
  id:
    | '__root__'
    | '/'
    | '/campaigns/$campaignId'
    | '/directory/$campaignId'
    | '/join/$code'
    | '/campaigns/'
    | '/characters/'
    | '/directory/'
    | '/characters/$characterId/build'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  DirectoryCampaignIdRoute: typeof DirectoryCampaignIdRoute
  JoinCodeRoute: typeof JoinCodeRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  CharactersCharacterIdBuildRoute: typeof CharactersCharacterIdBuildRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/$campaignId': {
      id: '/directory/$campaignId'
      path: '/directory/$campaignId'
      fullPath: '/directory/$campaignId'
      preLoaderRoute: typeof DirectoryCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterId/build': {
      id: '/characters/$characterId/build'
      path: '/characters/$characterId/build'
      fullPath: '/characters/$characterId/build'
      preLoaderRoute: typeof CharactersCharacterIdBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  DirectoryCampaignIdRoute: DirectoryCampaignIdRoute,
  JoinCodeRoute: JoinCodeRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
  CharactersCharacterIdBuildRoute: CharactersCharacterIdBuildRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
